import { useEffect, useState } from 'react';
import { Autocomplete, Box, Button, Checkbox, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, LinearProgress, Pagination, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { completeTireOrder, createTireOrder, listTireOrders, revertTireOrder } from '../../api/tireOrderAdministrationApi';
import { usePermissions } from '../../context/permissioncontext';
import '../style/tireorders.css';
import '../style/tireorders-layout.css';
import '../style/tireorders-control-sizes.css';

const formatDate = (value) => value ? new Date(value).toLocaleString('vi-VN', { hour: '2-digit', minute: '2-digit', day: '2-digit', month: '2-digit', year: 'numeric' }) : '';
const formatMoney = (value) => `${Number(value || 0).toLocaleString('vi-VN')} VNĐ`;

const TireOrders = () => {
  const navigate = useNavigate(); const { can } = usePermissions();
  const [data, setData] = useState({ items: [], pagination: {} }); const [loading, setLoading] = useState(true); const [filters, setFilters] = useState({ search: '', creator: '', status: '', from: '', to: '' }); const [suggestions, setSuggestions] = useState({ orderNames: [], creators: [] }); const [page, setPage] = useState(1); const [limit, setLimit] = useState(10); const [createDialogOpen, setCreateDialogOpen] = useState(false); const [newOrderName, setNewOrderName] = useState(''); const [creating, setCreating] = useState(false); const [statusDialogOrder, setStatusDialogOrder] = useState(null); const [updatingStatus, setUpdatingStatus] = useState(false);
  const load = async (targetPage = page, nextLimit = limit) => { setLoading(true); try { setData(await listTireOrders({ ...filters, page: targetPage, limit: nextLimit })); setPage(targetPage); } catch (error) { toast.error(error.message); } finally { setLoading(false); } };
  // Chỉ áp dụng bộ lọc sau khi người dùng bấm nút Lọc.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load(1); listTireOrders({ limit: 100 }).then((result) => setSuggestions({ orderNames: [...new Set(result.items.map((item) => item.orderName).filter(Boolean))], creators: [...new Set(result.items.map((item) => item.createdByName).filter(Boolean))] })).catch(() => {}); }, []);
  const openCreateDialog = () => { setNewOrderName(''); setCreateDialogOpen(true); };
  const create = async (event) => { event?.preventDefault(); if (!newOrderName.trim() || creating) return; setCreating(true); try { const { order } = await createTireOrder({ orderName: newOrderName.trim() }); navigate(`/tire-orders/${order._id}`); } catch (error) { toast.error(error.message); setCreating(false); } };
  const changeStatus = async () => {
    if (!statusDialogOrder || updatingStatus) return;
    setUpdatingStatus(true);
    try {
      if (statusDialogOrder.status === 'completed') await revertTireOrder(statusDialogOrder._id, { expectedVersion: statusDialogOrder.version });
      else await completeTireOrder(statusDialogOrder._id, { expectedVersion: statusDialogOrder.version });
      toast.success(statusDialogOrder.status === 'completed' ? 'Đã hủy hoàn thành đơn.' : 'Đã hoàn thành đơn.');
      setStatusDialogOrder(null);
      await load(page);
    } catch (error) { toast.error(error.message); } finally { setUpdatingStatus(false); }
  };
  const count = data.pagination.totalItems || 0; const from = count ? (page - 1) * limit + 1 : 0; const to = Math.min(page * limit, count);
  return <Box className="inventory-order-list-page tire-orders-page" p={2}>
    <Paper className="tire-orders-filter-card" component="section"><Typography variant="h5" className="tire-orders-heading">Quản lý phụ tùng xe</Typography><Stack className="tire-orders-filters" direction="row" flexWrap="wrap" useFlexGap spacing={1}>{can('tireorder.create') && <Button className="tire-orders-create" variant="contained" startIcon={<AddIcon />} onClick={openCreateDialog}>Tạo đơn mới</Button>}<Autocomplete className="tire-orders-filter-autocomplete tire-orders-name-filter" freeSolo autoHighlight options={suggestions.orderNames} inputValue={filters.search} onInputChange={(_, value) => setFilters((current) => ({ ...current, search: value }))} renderInput={(params) => <TextField {...params} label="Tên đơn" placeholder="Nhập tên..." />} /><Autocomplete className="tire-orders-filter-autocomplete tire-orders-creator-filter" freeSolo autoHighlight options={suggestions.creators} inputValue={filters.creator} onInputChange={(_, value) => setFilters((current) => ({ ...current, creator: value }))} renderInput={(params) => <TextField {...params} label="Người tạo" placeholder="Nhập người tạo..." />} /><TextField className="tire-orders-status-filter" select label="Trạng thái" InputLabelProps={{ shrink: true }} value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })} SelectProps={{ native: true }}><option value="">Tất cả</option><option value="processing">Đang xử lý</option><option value="completed">Hoàn thành</option></TextField><TextField className="tire-orders-date-filter" label="Từ ngày" type="date" InputLabelProps={{ shrink: true }} value={filters.from} onChange={(event) => setFilters({ ...filters, from: event.target.value })} /><TextField className="tire-orders-date-filter" label="Đến ngày" type="date" InputLabelProps={{ shrink: true }} value={filters.to} onChange={(event) => setFilters({ ...filters, to: event.target.value })} /><Button className="tire-orders-apply" variant="contained" onClick={() => load(1)}>Lọc</Button></Stack></Paper>
    <Box className="inventory-order-list-region tire-orders-table-region" mt={1.75}>{loading && !data.items.length ? <Box textAlign="center" p={5}><CircularProgress /></Box> : <>{loading && <LinearProgress sx={{ mb: 1 }} />}<TableContainer component={Paper} className="inventory-order-list-table tire-orders-table" sx={{ overflow: 'auto' }}><Table stickyHeader style={{ minWidth: '1200px', tableLayout: 'fixed' }} aria-label="Danh sách đơn lốp"><TableHead><TableRow><TableCell align="center" sx={{ width: '20%' }}>Tên đơn</TableCell><TableCell align="center" sx={{ width: '12%' }}>Tên người tạo</TableCell><TableCell align="center" sx={{ width: '8%' }}>Số xe</TableCell><TableCell align="center" sx={{ width: '8%' }}>Tổng lốp</TableCell><TableCell align="center" sx={{ width: '12%' }}>Tổng tiền</TableCell><TableCell align="center" sx={{ width: '8%' }}>Trạng thái</TableCell><TableCell align="center" sx={{ width: '12%' }}>Ngày tạo</TableCell><TableCell align="center" sx={{ width: '12%' }}>Ngày thực hiện</TableCell><TableCell align="center" sx={{ width: '12%' }}>Ngày hoàn thành</TableCell><TableCell align="center" sx={{ width: 100 }} /></TableRow></TableHead><TableBody>{data.items.map((order) => <TableRow key={order._id} hover><TableCell align="center">{order.orderName || '—'}</TableCell><TableCell align="center">{order.createdByName || '—'}</TableCell><TableCell align="center">{order.totalVehicles} xe</TableCell><TableCell align="center">{order.totalTires} lốp</TableCell><TableCell align="center">{formatMoney(order.totalExportPrice)}</TableCell><TableCell align="center"><Checkbox checked={order.status === 'completed'} color="success" disabled={!can('tireorder.edit') || updatingStatus} onChange={() => setStatusDialogOrder(order)} inputProps={{ 'aria-label': order.status === 'completed' ? 'Hủy hoàn thành đơn' : 'Hoàn thành đơn' }} /></TableCell><TableCell align="center">{formatDate(order.createdAt)}</TableCell><TableCell align="center">{formatDate(order.transactionDate)}</TableCell><TableCell align="center">{formatDate(order.completedAt)}</TableCell><TableCell align="center"><Button variant="contained" color="primary" size="small" onClick={() => navigate(`/tire-orders/${order._id}`)}>Chi tiết</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer></>}</Box>
    <Stack className="tire-orders-footer" direction={{ xs: 'column', md: 'row' }} alignItems={{ md: 'center' }} justifyContent="space-between" spacing={1.5}><Typography color="text.secondary">Hiển thị {from} đến {to} của {count} đơn lốp</Typography><Pagination count={data.pagination.totalPages || 1} page={page} onChange={(_, value) => load(value)} siblingCount={1} boundaryCount={1} /><TextField select value={limit} onChange={(event) => { const nextLimit = Number(event.target.value); setLimit(nextLimit); load(1, nextLimit); }} SelectProps={{ native: true }} className="tire-orders-page-size"><option value={10}>10 / trang</option><option value={20}>20 / trang</option><option value={50}>50 / trang</option></TextField></Stack>
    <Dialog open={createDialogOpen} onClose={() => !creating && setCreateDialogOpen(false)} fullWidth maxWidth="xs"><Box component="form" onSubmit={create}><DialogTitle>Tạo đơn lốp mới</DialogTitle><DialogContent><Typography color="text.secondary" variant="body2" sx={{ mb: 2 }}>Nhập tên để tạo đơn đang xử lý. Sau đó bạn sẽ được chuyển thẳng tới trang chi tiết để thêm xe và lốp.</Typography><TextField autoFocus required fullWidth label="Tên đơn lốp" placeholder="Ví dụ: Thay lốp xe tải tháng 8" value={newOrderName} onChange={(event) => setNewOrderName(event.target.value)} inputProps={{ maxLength: 160 }} /></DialogContent><DialogActions><Button disabled={creating} onClick={() => setCreateDialogOpen(false)}>Hủy</Button><Button type="submit" variant="contained" disabled={!newOrderName.trim() || creating}>{creating ? 'Đang tạo...' : 'Tạo đơn'}</Button></DialogActions></Box></Dialog>
    <Dialog open={Boolean(statusDialogOrder)} onClose={() => !updatingStatus && setStatusDialogOrder(null)} fullWidth maxWidth="xs"><DialogTitle>{statusDialogOrder?.status === 'completed' ? 'Xác nhận hủy hoàn thành' : 'Xác nhận hoàn thành đơn'}</DialogTitle><DialogContent><Typography>{statusDialogOrder?.status === 'completed' ? 'Hủy hoàn thành sẽ hoàn lại toàn bộ số lốp đã trừ kho và đưa đơn về trạng thái đang xử lý. Bạn có chắc chắn muốn tiếp tục?' : 'Hoàn thành đơn sẽ trừ tồn kho của toàn bộ lốp trong đơn. Bạn có chắc chắn muốn tiếp tục?'}</Typography></DialogContent><DialogActions><Button disabled={updatingStatus} onClick={() => setStatusDialogOrder(null)}>Hủy</Button><Button variant="contained" color={statusDialogOrder?.status === 'completed' ? 'warning' : 'primary'} disabled={updatingStatus} onClick={changeStatus}>{updatingStatus ? 'Đang xử lý...' : 'Xác nhận'}</Button></DialogActions></Dialog>
  </Box>;
};

export default TireOrders;
